// Code generated by protoc-gen-go. DO NOT EDIT.
// source: card.proto

/*
Package cardproto is a generated protocol buffer package.

It is generated from these files:
	card.proto

It has these top-level messages:
	CardBlockSyncRequest
	CardBlockSyncResponse
	CardBlocksFetchRequest
	CardBlockFetchResponse
	CardBlockPushRequest
	CardBlockReceive
	CardBlock
*/
package cardproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CardBlockSyncRequest struct {
	Height int64  `protobuf:"varint,1,opt,name=Height" json:"Height,omitempty"`
	CardID string `protobuf:"bytes,2,opt,name=CardID" json:"CardID,omitempty"`
}

func (m *CardBlockSyncRequest) Reset()                    { *m = CardBlockSyncRequest{} }
func (m *CardBlockSyncRequest) String() string            { return proto.CompactTextString(m) }
func (*CardBlockSyncRequest) ProtoMessage()               {}
func (*CardBlockSyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CardBlockSyncRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CardBlockSyncRequest) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

type CardBlockSyncResponse struct {
	Valid      bool   `protobuf:"varint,1,opt,name=Valid" json:"Valid,omitempty"`
	Height     int64  `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	CardID     string `protobuf:"bytes,3,opt,name=CardID" json:"CardID,omitempty"`
	PrevCardID string `protobuf:"bytes,4,opt,name=PrevCardID" json:"PrevCardID,omitempty"`
}

func (m *CardBlockSyncResponse) Reset()                    { *m = CardBlockSyncResponse{} }
func (m *CardBlockSyncResponse) String() string            { return proto.CompactTextString(m) }
func (*CardBlockSyncResponse) ProtoMessage()               {}
func (*CardBlockSyncResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CardBlockSyncResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CardBlockSyncResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CardBlockSyncResponse) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *CardBlockSyncResponse) GetPrevCardID() string {
	if m != nil {
		return m.PrevCardID
	}
	return ""
}

type CardBlocksFetchRequest struct {
	Height int64 `protobuf:"varint,1,opt,name=Height" json:"Height,omitempty"`
}

func (m *CardBlocksFetchRequest) Reset()                    { *m = CardBlocksFetchRequest{} }
func (m *CardBlocksFetchRequest) String() string            { return proto.CompactTextString(m) }
func (*CardBlocksFetchRequest) ProtoMessage()               {}
func (*CardBlocksFetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CardBlocksFetchRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type CardBlockFetchResponse struct {
	Valid      bool         `protobuf:"varint,1,opt,name=Valid" json:"Valid,omitempty"`
	CardBlocks []*CardBlock `protobuf:"bytes,2,rep,name=CardBlocks" json:"CardBlocks,omitempty"`
}

func (m *CardBlockFetchResponse) Reset()                    { *m = CardBlockFetchResponse{} }
func (m *CardBlockFetchResponse) String() string            { return proto.CompactTextString(m) }
func (*CardBlockFetchResponse) ProtoMessage()               {}
func (*CardBlockFetchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CardBlockFetchResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CardBlockFetchResponse) GetCardBlocks() []*CardBlock {
	if m != nil {
		return m.CardBlocks
	}
	return nil
}

type CardBlockPushRequest struct {
	CardBlock *CardBlock `protobuf:"bytes,1,opt,name=CardBlock" json:"CardBlock,omitempty"`
}

func (m *CardBlockPushRequest) Reset()                    { *m = CardBlockPushRequest{} }
func (m *CardBlockPushRequest) String() string            { return proto.CompactTextString(m) }
func (*CardBlockPushRequest) ProtoMessage()               {}
func (*CardBlockPushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CardBlockPushRequest) GetCardBlock() *CardBlock {
	if m != nil {
		return m.CardBlock
	}
	return nil
}

type CardBlockReceive struct {
	CardBlock *CardBlock `protobuf:"bytes,1,opt,name=CardBlock" json:"CardBlock,omitempty"`
}

func (m *CardBlockReceive) Reset()                    { *m = CardBlockReceive{} }
func (m *CardBlockReceive) String() string            { return proto.CompactTextString(m) }
func (*CardBlockReceive) ProtoMessage()               {}
func (*CardBlockReceive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CardBlockReceive) GetCardBlock() *CardBlock {
	if m != nil {
		return m.CardBlock
	}
	return nil
}

type CardBlock struct {
	Version    string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Hard       int32  `protobuf:"varint,2,opt,name=Hard" json:"Hard,omitempty"`
	PubKey     string `protobuf:"bytes,3,opt,name=PubKey" json:"PubKey,omitempty"`
	Timestamp  int64  `protobuf:"varint,4,opt,name=Timestamp" json:"Timestamp,omitempty"`
	RandNumber int32  `protobuf:"varint,5,opt,name=RandNumber" json:"RandNumber,omitempty"`
	PrevCardID string `protobuf:"bytes,6,opt,name=PrevCardID" json:"PrevCardID,omitempty"`
	Height     int64  `protobuf:"varint,7,opt,name=Height" json:"Height,omitempty"`
}

func (m *CardBlock) Reset()                    { *m = CardBlock{} }
func (m *CardBlock) String() string            { return proto.CompactTextString(m) }
func (*CardBlock) ProtoMessage()               {}
func (*CardBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CardBlock) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CardBlock) GetHard() int32 {
	if m != nil {
		return m.Hard
	}
	return 0
}

func (m *CardBlock) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *CardBlock) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CardBlock) GetRandNumber() int32 {
	if m != nil {
		return m.RandNumber
	}
	return 0
}

func (m *CardBlock) GetPrevCardID() string {
	if m != nil {
		return m.PrevCardID
	}
	return ""
}

func (m *CardBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*CardBlockSyncRequest)(nil), "cardproto.CardBlockSyncRequest")
	proto.RegisterType((*CardBlockSyncResponse)(nil), "cardproto.CardBlockSyncResponse")
	proto.RegisterType((*CardBlocksFetchRequest)(nil), "cardproto.CardBlocksFetchRequest")
	proto.RegisterType((*CardBlockFetchResponse)(nil), "cardproto.CardBlockFetchResponse")
	proto.RegisterType((*CardBlockPushRequest)(nil), "cardproto.CardBlockPushRequest")
	proto.RegisterType((*CardBlockReceive)(nil), "cardproto.CardBlockReceive")
	proto.RegisterType((*CardBlock)(nil), "cardproto.CardBlock")
}

func init() { proto.RegisterFile("card.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0x4d, 0xff, 0xfc, 0x32, 0xbf, 0x8b, 0x2c, 0xb5, 0xe4, 0x20, 0x12, 0xf6, 0x94, 0x53,
	0x90, 0xea, 0x27, 0x50, 0x09, 0x55, 0x41, 0xc2, 0x2a, 0xbd, 0x6f, 0xb2, 0x83, 0x0d, 0x36, 0x7f,
	0xdc, 0x4d, 0x0a, 0x3d, 0xf8, 0xf9, 0xfc, 0x5a, 0x92, 0x6d, 0x9a, 0x2c, 0x81, 0x2a, 0x78, 0x9b,
	0xf7, 0x66, 0xde, 0x9b, 0xdd, 0x79, 0x00, 0x09, 0x97, 0x22, 0x28, 0x65, 0x51, 0x15, 0xc4, 0x69,
	0x6a, 0x5d, 0xd2, 0x10, 0xe6, 0x77, 0x5c, 0x8a, 0xdb, 0x6d, 0x91, 0xbc, 0xbf, 0xec, 0xf3, 0x84,
	0xe1, 0x47, 0x8d, 0xaa, 0x22, 0x0b, 0x98, 0xae, 0x30, 0x7d, 0xdb, 0x54, 0xae, 0xe5, 0x59, 0xbe,
	0xcd, 0x5a, 0xd4, 0xf0, 0xcd, 0xfc, 0xc3, 0xbd, 0x3b, 0xf2, 0x2c, 0xdf, 0x61, 0x2d, 0xa2, 0x9f,
	0x70, 0x3e, 0xf0, 0x51, 0x65, 0x91, 0x2b, 0x24, 0x73, 0x98, 0xac, 0xf9, 0x36, 0x15, 0xda, 0xe7,
	0x1f, 0x3b, 0x00, 0xc3, 0x7e, 0x74, 0xc2, 0xde, 0x36, 0xed, 0xc9, 0x25, 0x40, 0x24, 0x71, 0xd7,
	0xf6, 0xc6, 0xba, 0x67, 0x30, 0xf4, 0x0a, 0x16, 0xdd, 0x7a, 0x15, 0x62, 0x95, 0x6c, 0x7e, 0xf9,
	0x08, 0x15, 0x86, 0xa2, 0x15, 0xfc, 0xf8, 0xe2, 0x1b, 0x80, 0x7e, 0x83, 0x3b, 0xf2, 0x6c, 0xff,
	0xff, 0x72, 0x1e, 0x74, 0x87, 0x0c, 0xba, 0x26, 0x33, 0xe6, 0xe8, 0xa3, 0x71, 0xde, 0xa8, 0x56,
	0xdd, 0xab, 0x96, 0xe0, 0x74, 0xbc, 0xde, 0x73, 0xca, 0xac, 0x1f, 0xa3, 0x21, 0x9c, 0xf5, 0x3c,
	0x26, 0x98, 0xee, 0xf0, 0x4f, 0x3e, 0x5f, 0x96, 0x21, 0x22, 0x2e, 0xcc, 0xd6, 0x28, 0x55, 0x5a,
	0xe4, 0x5a, 0xef, 0xb0, 0x23, 0x24, 0x04, 0xc6, 0x2b, 0x2e, 0x85, 0x4e, 0x68, 0xc2, 0x74, 0xdd,
	0x5c, 0x33, 0xaa, 0xe3, 0x27, 0xdc, 0x1f, 0xf3, 0x39, 0x20, 0x72, 0x01, 0xce, 0x6b, 0x9a, 0xa1,
	0xaa, 0x78, 0x56, 0xea, 0x78, 0x6c, 0xd6, 0x13, 0x4d, 0x7a, 0x8c, 0xe7, 0xe2, 0xb9, 0xce, 0x62,
	0x94, 0xee, 0x44, 0xfb, 0x19, 0xcc, 0x20, 0xdd, 0xe9, 0x30, 0x5d, 0x23, 0xc3, 0x99, 0x99, 0x61,
	0x3c, 0xd5, 0xbf, 0xbc, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xce, 0x73, 0x7d, 0xae, 0xdc, 0x02,
	0x00, 0x00,
}
