// Generated by github.com/davyxu/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: card.proto

package cardproto

import (
	"github.com/davyxu/cellnet"
	"reflect"
	_ "github.com/davyxu/cellnet/codec/pb"
)

func init() {

	// card.proto
	cellnet.RegisterMessageMeta("pb", "cardproto.CardBlockFetch", reflect.TypeOf((*CardBlockFetch)(nil)).Elem(), 72977303)
	cellnet.RegisterMessageMeta("pb", "cardproto.CardBlockDig", reflect.TypeOf((*CardBlockDig)(nil)).Elem(), 2691297634)
	cellnet.RegisterMessageMeta("pb", "cardproto.CardBlockReceive", reflect.TypeOf((*CardBlockReceive)(nil)).Elem(), 2626273397)

}
